version: 1.2
workflows:
   - name: demo-fastqc-wf
     subclass: nfl
     primaryDescriptorPath: /nextflow.config
     testParameterFiles:
          -  /demo-fastqc-wf/tests/test-job-1.json
     filters:
         branches:
             - main
   - name: demo-fastqc-wf2
     subclass: nfl
     primaryDescriptorPath: /demo-fastqc-wf/nextflow.config
     testParameterFiles:
          -  /demo-fastqc-wf/tests/test-job-1.json
     filters:
         branches:
             - main             
   - name: actual-demo-fastqc
     subclass: nfl
     primaryDescriptorPath: /demo-fastqc/nextflow.config
     testParameterFiles:
          - /demo-fastqc/tests/test-job-1.json
     filters:
         branches:
             - main 
